version: 0.2

env:
  variables:
    REPO_URI: "github.com/iseepurplesquids/simple"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Starting"

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - $(aws ecr get-login --registry-id 148483637873 --region ap-south-1 --no-include-email)

  build:
    commands:
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION - $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  post_build:
    commands:

      # - echo "    building image and generating client [start]"
      # - make build_dev
      # - echo "    building image and generating client [done]"
      # - echo "ECR_REPOSITORY_URI_DEFAULT - $ECR_REPOSITORY_URI_DEFAULT"
      # - echo "    pushing the image to ECR [start]"
      # - docker push $ECR_REPOSITORY_URI_DEFAULT:latest-dev
      # - echo "    pushing the image to ECR [done]"

      - echo "PWD - $(pwd)  CODEBUILD_SRC_DIR - "$CODEBUILD_SRC_DIR""
      - echo "Running Migration"
      - make migrate